// Fallback Master presets, mirrored from the backend's
// constants/categories.js. Used to populate the sheet's Master suggestions
// instantly; api/meta.js refreshes these from the server so the two stay in
// sync if the backend list changes. Free text is always allowed too — these
// are just suggestions, not a locked list.
export const DEFAULT_EXPENSE_MASTERS = [
  "Raw Timber Purchase",
  "Transport & Freight",
  "Labor Wages",
  "Loading & Unloading",
  "Sawmill & Machinery Maintenance",
  "Fuel & Diesel",
  "Service & Maintenance",
  "Tyre & Puncture",
  "Spare Parts",
  "Toll & Parking",
  "Vehicle Insurance Premium",
  "Permit & Fitness Fees",
  "Driver Wages",
  "Fines & Challans",
  "Vehicle Expenses",
  // 21 Sep, per Rishi: his real paper-ledger master names, mirrored from
  // backend/constants/categories.js — keep the two files in sync.
  "Mill Thekedar",
  "Pilling Thekedar",
  "Repso Thekedar",
  "Loading Thekedar",
  "Bundle Thekedar",
  "Lafa Thekedar",
  "Auto M Payment",
  "Labour Charges",
  "Repso Loading Charges",
  "Payment",
  "Mill Running Exp",
  "Staff Exp",
  "Office Exp",
  "Stationary Exp",
  "Mess Exp",
  "Medical Exp",
  "Store Exp",
  "TP Charges",
  "Mill No-1 (New)",
  "Kushal",
  "Electricity Bill",
  "Rent",
  "GST & Taxes",
  "Packing Material",
  "Office & Stationery",
  "Miscellaneous",
];
